/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import javax.swing.JOptionPane;

/**
 *
 * @author esperant
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public AdminView() {
        this.setLocation(300, 100);
        this.setTitle("Arles Car Rental");
        this.setResizable(true);
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiniFrame = new javax.swing.JInternalFrame();
        Tabs = new javax.swing.JTabbedPane();
        tabFinance = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        cmdOk2 = new javax.swing.JButton();
        cmdCancel2 = new javax.swing.JButton();
        tabBills = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cmdOk1 = new javax.swing.JButton();
        cmdCancel1 = new javax.swing.JButton();
        tabBankAcc = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmdCancel = new javax.swing.JButton();
        cmdOk = new javax.swing.JButton();
        MiniFrame_New_Staff = new javax.swing.JInternalFrame();
        New_Staff = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox1 = new javax.swing.JComboBox();
        rdFemale = new javax.swing.JRadioButton();
        rdMale = new javax.swing.JRadioButton();
        txtSurname = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmdSave1 = new javax.swing.JButton();
        cmdCancel4 = new javax.swing.JButton();
        MiniFrame_Staff_Records = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRented = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        MiniFrame_StaffRecords = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStaff_Records = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        MiniFrame_NewCar = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        cmdSave = new javax.swing.JButton();
        cmdCancel3 = new javax.swing.JButton();
        MiniFrame_History = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRented1 = new javax.swing.JTable();
        cmdClose = new javax.swing.JButton();
        MiniFrame_Rented = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        cmdCancel7 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblRented2 = new javax.swing.JTable();
        MiniFrame_Available = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        cmdCancel8 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblRented3 = new javax.swing.JTable();
        MiniFrame_Maintenance = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        cmdCancel6 = new javax.swing.JButton();
        MiniFrame_Insurance = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        cmdCancel5 = new javax.swing.JButton();
        MiniFrame_Clients = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        cmdClose1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblRented5 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        cmdHome = new javax.swing.JMenu();
        cmdClients = new javax.swing.JMenu();
        cmdStaff = new javax.swing.JMenu();
        cmdNew_Staff = new javax.swing.JMenuItem();
        cmdStaff_Records = new javax.swing.JMenuItem();
        cmdMgt = new javax.swing.JMenu();
        cmdFinance = new javax.swing.JMenuItem();
        cmdInsurance = new javax.swing.JMenuItem();
        cmdVehicle = new javax.swing.JMenu();
        cmdAvailable = new javax.swing.JMenuItem();
        cmdNewCar = new javax.swing.JMenuItem();
        cmdRented = new javax.swing.JMenuItem();
        cmdHistory = new javax.swing.JMenuItem();
        cmdMaintain = new javax.swing.JMenu();
        cmdMaintenance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        MiniFrame.setFocusTraversalPolicyProvider(true);
        MiniFrame.setVerifyInputWhenFocusTarget(false);
        MiniFrame.setVisible(false);
        MiniFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdOk2.setText("OK");
        cmdOk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOk2ActionPerformed(evt);
            }
        });

        cmdCancel2.setText("CANCEL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(637, Short.MAX_VALUE)
                .addComponent(cmdOk2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCancel2)
                .addGap(4, 4, 4))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 351, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdOk2)
                    .addComponent(cmdCancel2)))
        );

        tabFinance.addTab("Finance ", jPanel3);

        Tabs.addTab("Finance ", tabFinance);

        cmdOk1.setText("OK");
        cmdOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOk1ActionPerformed(evt);
            }
        });

        cmdCancel1.setText("CANCEL");
        cmdCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(cmdOk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCancel1)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 351, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdOk1)
                    .addComponent(cmdCancel1)))
        );

        tabBills.addTab("Bills", jPanel2);

        Tabs.addTab("Bills", tabBills);

        cmdCancel.setText("CANCEL");

        cmdOk.setText("OK");
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(cmdOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCancel)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 351, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdOk)))
        );

        tabBankAcc.addTab("Bank Accounts", jPanel1);

        Tabs.addTab("Bank Accounts", tabBankAcc);

        MiniFrame.getContentPane().add(Tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 430));

        getContentPane().add(MiniFrame);

        MiniFrame_New_Staff.setVerifyInputWhenFocusTarget(false);
        MiniFrame_New_Staff.setVisible(false);
        MiniFrame_New_Staff.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        New_Staff.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 2, 14), java.awt.Color.blue)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "Jan", "Fab", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select here", "Bachelor", "Certificate", "Diploma" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        rdFemale.setText("Female");

        rdMale.setText("Male");

        jLabel2.setText("Gender");

        jLabel8.setText("Postal Address");

        jLabel4.setText("Qualification");

        jLabel5.setText("Mobile");

        jLabel1.setText("Name");

        jLabel6.setText("Email");

        jLabel3.setText("D.O.B");

        jLabel9.setText("Username");

        jLabel10.setText("Password");

        jLabel7.setText("Field");

        jLabel11.setText("Surname");

        cmdSave1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        cmdSave1.setText("Save");
        cmdSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSave1ActionPerformed(evt);
            }
        });

        cmdCancel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        cmdCancel4.setText("Cancel");
        cmdCancel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdCancel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout New_StaffLayout = new javax.swing.GroupLayout(New_Staff);
        New_Staff.setLayout(New_StaffLayout);
        New_StaffLayout.setHorizontalGroup(
            New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_StaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_StaffLayout.createSequentialGroup()
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(New_StaffLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(New_StaffLayout.createSequentialGroup()
                                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(New_StaffLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(rdMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdFemale))
                            .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmdSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(New_StaffLayout.createSequentialGroup()
                                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(New_StaffLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmail)
                                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, New_StaffLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(New_StaffLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmdCancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(New_StaffLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_StaffLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        New_StaffLayout.setVerticalGroup(
            New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_StaffLayout.createSequentialGroup()
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(New_StaffLayout.createSequentialGroup()
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdMale)
                            .addComponent(rdFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(New_StaffLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(New_StaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSave1)
                    .addComponent(cmdCancel4))
                .addContainerGap())
        );

        MiniFrame_New_Staff.getContentPane().add(New_Staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        getContentPane().add(MiniFrame_New_Staff);

        MiniFrame_Staff_Records.setVisible(false);

        tblRented.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Surname", "Driving  license ", "Rented Car", "Sign In", "Sign Out", "Served By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRented);
        if (tblRented.getColumnModel().getColumnCount() > 0) {
            tblRented.getColumnModel().getColumn(2).setResizable(false);
            tblRented.getColumnModel().getColumn(4).setHeaderValue("Rented Car");
            tblRented.getColumnModel().getColumn(5).setHeaderValue("Sign In");
            tblRented.getColumnModel().getColumn(6).setHeaderValue("Sign Out");
            tblRented.getColumnModel().getColumn(7).setHeaderValue("Served By");
        }

        jButton3.setText("Close");

        javax.swing.GroupLayout MiniFrame_Staff_RecordsLayout = new javax.swing.GroupLayout(MiniFrame_Staff_Records.getContentPane());
        MiniFrame_Staff_Records.getContentPane().setLayout(MiniFrame_Staff_RecordsLayout);
        MiniFrame_Staff_RecordsLayout.setHorizontalGroup(
            MiniFrame_Staff_RecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_Staff_RecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiniFrame_Staff_RecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1628, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_Staff_RecordsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        MiniFrame_Staff_RecordsLayout.setVerticalGroup(
            MiniFrame_Staff_RecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_Staff_RecordsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(782, Short.MAX_VALUE))
        );

        getContentPane().add(MiniFrame_Staff_Records);

        MiniFrame_StaffRecords.setVisible(false);

        tblStaff_Records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Photo", "ID", "Name", "Surname", "Gender", "National ID", "Driving  license "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblStaff_Records);
        if (tblStaff_Records.getColumnModel().getColumnCount() > 0) {
            tblStaff_Records.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton4.setText("Close");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MiniFrame_StaffRecordsLayout = new javax.swing.GroupLayout(MiniFrame_StaffRecords.getContentPane());
        MiniFrame_StaffRecords.getContentPane().setLayout(MiniFrame_StaffRecordsLayout);
        MiniFrame_StaffRecordsLayout.setHorizontalGroup(
            MiniFrame_StaffRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1648, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_StaffRecordsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        MiniFrame_StaffRecordsLayout.setVerticalGroup(
            MiniFrame_StaffRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_StaffRecordsLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 787, Short.MAX_VALUE))
        );

        getContentPane().add(MiniFrame_StaffRecords);

        MiniFrame_NewCar.setVisible(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 16))); // NOI18N

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 1, true));

        jLabel12.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel12.setText("Car Model");

        jLabel13.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel13.setText("Campany");

        jLabel14.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel14.setText("Make Year");

        jLabel15.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel15.setText("Seats");

        jLabel16.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel16.setText("Engine Capacity");

        jLabel17.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel17.setText("Type");

        jLabel18.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel18.setText("Rent Fee");

        jLabel19.setFont(new java.awt.Font("Garamond", 1, 16)); // NOI18N
        jLabel19.setText("per Day");

        jTextField10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic", "Manual" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "5", "7", "8", "15" }));

        jLabel20.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        jLabel20.setText("Reg. Number");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfa Romeo", "AstonMartin", "Audi", "Bentley", "BMW", "Bugatti", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Citroen", "Dodge", "Ferrari", "Fiat", "Ford", "Geely", "General Motors", "GMC", "Honda", "Hyundai", "Infiniti", "Jaguar", "Jeep", "Kia", "Lamborghini", "Land", "Rover", "Lexus", "Maserati", "Mazda", "McLaren", "MercedesBenz", "Mini", "Mitsubishi", "Nissan", "Peugeot", "Porsche", "Renault", "Rolls Royce", "Subaru", "Suzuki", "Tata Motors", "Tesla", "Toyota", "Volkswagen", "Volvo" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(7, 7, 7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addGap(13, 13, 13)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField2)
                                        .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(65, 65, 65)
                                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(22, 22, 22)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        cmdSave.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        cmdSave.setText("Save");
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdCancel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        cmdCancel3.setText("Cancel");
        cmdCancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSave)
                    .addComponent(cmdCancel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout MiniFrame_NewCarLayout = new javax.swing.GroupLayout(MiniFrame_NewCar.getContentPane());
        MiniFrame_NewCar.getContentPane().setLayout(MiniFrame_NewCarLayout);
        MiniFrame_NewCarLayout.setHorizontalGroup(
            MiniFrame_NewCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_NewCarLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1001, Short.MAX_VALUE))
        );
        MiniFrame_NewCarLayout.setVerticalGroup(
            MiniFrame_NewCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_NewCarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(845, Short.MAX_VALUE))
        );

        getContentPane().add(MiniFrame_NewCar);

        MiniFrame_History.setVisible(false);

        tblRented1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Rented Car", "Sign In", "Sign Out", "Duration", "Condition", "Served By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblRented1);

        cmdClose.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        cmdClose.setText("Close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiniFrame_HistoryLayout = new javax.swing.GroupLayout(MiniFrame_History.getContentPane());
        MiniFrame_History.getContentPane().setLayout(MiniFrame_HistoryLayout);
        MiniFrame_HistoryLayout.setHorizontalGroup(
            MiniFrame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiniFrame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1628, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_HistoryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdClose)))
                .addContainerGap())
        );
        MiniFrame_HistoryLayout.setVerticalGroup(
            MiniFrame_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_HistoryLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdClose)
                .addGap(0, 780, Short.MAX_VALUE))
        );

        getContentPane().add(MiniFrame_History);

        MiniFrame_Rented.setVisible(false);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancel7.setText("CANCEL");
        cmdCancel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel7ActionPerformed(evt);
            }
        });

        tblRented2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Rented Car", "Sign In", "Sign Out", "Duration", "Condition", "Served By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblRented2);

        javax.swing.GroupLayout MiniFrame_RentedLayout = new javax.swing.GroupLayout(MiniFrame_Rented.getContentPane());
        MiniFrame_Rented.getContentPane().setLayout(MiniFrame_RentedLayout);
        MiniFrame_RentedLayout.setHorizontalGroup(
            MiniFrame_RentedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_RentedLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1465, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_RentedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCancel7)
                .addContainerGap())
            .addGroup(MiniFrame_RentedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1648, Short.MAX_VALUE))
        );
        MiniFrame_RentedLayout.setVerticalGroup(
            MiniFrame_RentedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_RentedLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1083, Short.MAX_VALUE)
                .addComponent(cmdCancel7)
                .addContainerGap())
            .addGroup(MiniFrame_RentedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5))
        );

        getContentPane().add(MiniFrame_Rented);

        MiniFrame_Available.setVisible(false);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancel8.setText("Cancel");
        cmdCancel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel8ActionPerformed(evt);
            }
        });

        tblRented3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "Rented Car", "Sign In", "Sign Out", "Duration", "Condition", "Served By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblRented3);

        javax.swing.GroupLayout MiniFrame_AvailableLayout = new javax.swing.GroupLayout(MiniFrame_Available.getContentPane());
        MiniFrame_Available.getContentPane().setLayout(MiniFrame_AvailableLayout);
        MiniFrame_AvailableLayout.setHorizontalGroup(
            MiniFrame_AvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_AvailableLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1543, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_AvailableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCancel8)
                .addContainerGap())
            .addGroup(MiniFrame_AvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1648, Short.MAX_VALUE))
        );
        MiniFrame_AvailableLayout.setVerticalGroup(
            MiniFrame_AvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_AvailableLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1095, Short.MAX_VALUE)
                .addComponent(cmdCancel8)
                .addContainerGap())
            .addGroup(MiniFrame_AvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
        );

        getContentPane().add(MiniFrame_Available);

        MiniFrame_Maintenance.setVisible(false);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancel6.setText("CANCEL");
        cmdCancel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiniFrame_MaintenanceLayout = new javax.swing.GroupLayout(MiniFrame_Maintenance.getContentPane());
        MiniFrame_Maintenance.getContentPane().setLayout(MiniFrame_MaintenanceLayout);
        MiniFrame_MaintenanceLayout.setHorizontalGroup(
            MiniFrame_MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_MaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_MaintenanceLayout.createSequentialGroup()
                .addContainerGap(1567, Short.MAX_VALUE)
                .addComponent(cmdCancel6)
                .addContainerGap())
        );
        MiniFrame_MaintenanceLayout.setVerticalGroup(
            MiniFrame_MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_MaintenanceLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1158, Short.MAX_VALUE)
                .addComponent(cmdCancel6)
                .addContainerGap())
        );

        getContentPane().add(MiniFrame_Maintenance);

        MiniFrame_Insurance.setVisible(false);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancel5.setText("CANCEL");
        cmdCancel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancel5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiniFrame_InsuranceLayout = new javax.swing.GroupLayout(MiniFrame_Insurance.getContentPane());
        MiniFrame_Insurance.getContentPane().setLayout(MiniFrame_InsuranceLayout);
        MiniFrame_InsuranceLayout.setHorizontalGroup(
            MiniFrame_InsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_InsuranceLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_InsuranceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCancel5)
                .addContainerGap())
        );
        MiniFrame_InsuranceLayout.setVerticalGroup(
            MiniFrame_InsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_InsuranceLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1087, Short.MAX_VALUE)
                .addComponent(cmdCancel5)
                .addContainerGap())
        );

        getContentPane().add(MiniFrame_Insurance);

        MiniFrame_Clients.setVisible(false);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdClose1.setText("Close");
        cmdClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClose1ActionPerformed(evt);
            }
        });

        tblRented5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Photo", "ID", "Name", "Surname", "Driving  license ", "Mobile"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblRented5);
        if (tblRented5.getColumnModel().getColumnCount() > 0) {
            tblRented5.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout MiniFrame_ClientsLayout = new javax.swing.GroupLayout(MiniFrame_Clients.getContentPane());
        MiniFrame_Clients.getContentPane().setLayout(MiniFrame_ClientsLayout);
        MiniFrame_ClientsLayout.setHorizontalGroup(
            MiniFrame_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_ClientsLayout.createSequentialGroup()
                .addGroup(MiniFrame_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniFrame_ClientsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdClose1))
                    .addGroup(MiniFrame_ClientsLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1648, Short.MAX_VALUE)
        );
        MiniFrame_ClientsLayout.setVerticalGroup(
            MiniFrame_ClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniFrame_ClientsLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdClose1)
                .addContainerGap())
        );

        getContentPane().add(MiniFrame_Clients);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel11);

        cmdHome.setText("Home");
        cmdHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdHomeMouseClicked(evt);
            }
        });
        cmdHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHomeActionPerformed(evt);
            }
        });
        MenuBar.add(cmdHome);

        cmdClients.setText("Clients");
        cmdClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdClientsMouseClicked(evt);
            }
        });
        MenuBar.add(cmdClients);

        cmdStaff.setText("Staff");
        cmdStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdStaffMouseClicked(evt);
            }
        });
        cmdStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStaffActionPerformed(evt);
            }
        });

        cmdNew_Staff.setText("New Employee");
        cmdNew_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdNew_StaffMouseClicked(evt);
            }
        });
        cmdNew_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNew_StaffActionPerformed(evt);
            }
        });
        cmdStaff.add(cmdNew_Staff);

        cmdStaff_Records.setText("Records");
        cmdStaff_Records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdStaff_RecordsMouseClicked(evt);
            }
        });
        cmdStaff_Records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStaff_RecordsActionPerformed(evt);
            }
        });
        cmdStaff.add(cmdStaff_Records);

        MenuBar.add(cmdStaff);

        cmdMgt.setText("Management");
        cmdMgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMgtActionPerformed(evt);
            }
        });

        cmdFinance.setText("Finance ");
        cmdFinance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFinanceActionPerformed(evt);
            }
        });
        cmdMgt.add(cmdFinance);

        cmdInsurance.setText("Insurance ");
        cmdInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInsuranceActionPerformed(evt);
            }
        });
        cmdMgt.add(cmdInsurance);

        MenuBar.add(cmdMgt);

        cmdVehicle.setText("Vehicle");

        cmdAvailable.setText("Available ");
        cmdAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAvailableActionPerformed(evt);
            }
        });
        cmdVehicle.add(cmdAvailable);

        cmdNewCar.setText("New Car");
        cmdNewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNewCarActionPerformed(evt);
            }
        });
        cmdVehicle.add(cmdNewCar);

        cmdRented.setText("Rented");
        cmdRented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRentedActionPerformed(evt);
            }
        });
        cmdVehicle.add(cmdRented);

        cmdHistory.setText("History");
        cmdHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHistoryActionPerformed(evt);
            }
        });
        cmdVehicle.add(cmdHistory);

        MenuBar.add(cmdVehicle);

        cmdMaintain.setText("Others");

        cmdMaintenance.setText("Maintenance ");
        cmdMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMaintenanceActionPerformed(evt);
            }
        });
        cmdMaintain.add(cmdMaintenance);

        MenuBar.add(cmdMaintain);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdFinanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFinanceActionPerformed
       this.MiniFrame.setVisible(true);
    }//GEN-LAST:event_cmdFinanceActionPerformed
//Ok Buttons
    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        this.MiniFrame.dispose();
    }//GEN-LAST:event_cmdOkActionPerformed

    private void cmdOk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOk2ActionPerformed
        this.MiniFrame.dispose();
    }//GEN-LAST:event_cmdOk2ActionPerformed

    private void cmdOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOk1ActionPerformed
        this.MiniFrame.dispose();
    }//GEN-LAST:event_cmdOk1ActionPerformed
//*****************************
    private void cmdMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMgtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMgtActionPerformed

    private void cmdHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHomeActionPerformed
       
    }//GEN-LAST:event_cmdHomeActionPerformed

    private void cmdHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdHomeMouseClicked
     
        this.MiniFrame.dispose();
        this.dispose();
    }//GEN-LAST:event_cmdHomeMouseClicked

    private void cmdNew_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNew_StaffActionPerformed
        this.MiniFrame_New_Staff.setVisible(true);
   
    }//GEN-LAST:event_cmdNew_StaffActionPerformed

    private void cmdSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSave1ActionPerformed
        this.MiniFrame_New_Staff.dispose();
        JOptionPane.showMessageDialog( null, "Saved" );
    }//GEN-LAST:event_cmdSave1ActionPerformed

    private void cmdCancel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCancel4MouseClicked
        this.MiniFrame_New_Staff.dispose();
    }//GEN-LAST:event_cmdCancel4MouseClicked

    private void cmdStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdStaffMouseClicked
       
    }//GEN-LAST:event_cmdStaffMouseClicked

    private void cmdRentedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRentedActionPerformed
       this.MiniFrame_Rented.setVisible(true);
    }//GEN-LAST:event_cmdRentedActionPerformed

    private void cmdStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdStaffActionPerformed

    private void cmdStaff_RecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdStaff_RecordsMouseClicked
       
    }//GEN-LAST:event_cmdStaff_RecordsMouseClicked

    private void cmdStaff_RecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStaff_RecordsActionPerformed
        this.MiniFrame_StaffRecords.setVisible(true);
                 
    }//GEN-LAST:event_cmdStaff_RecordsActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.MiniFrame_StaffRecords.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void cmdNew_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdNew_StaffMouseClicked
        
    }//GEN-LAST:event_cmdNew_StaffMouseClicked

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        this.MiniFrame_NewCar.dispose();
        JOptionPane.showMessageDialog( null, "Saved" );
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void cmdCancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel3ActionPerformed
        this.MiniFrame_NewCar.dispose();
    }//GEN-LAST:event_cmdCancel3ActionPerformed

    private void cmdNewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNewCarActionPerformed
        this.MiniFrame_NewCar.setVisible(true);
    }//GEN-LAST:event_cmdNewCarActionPerformed

    private void cmdHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHistoryActionPerformed
        this.MiniFrame_History.setVisible(true);
    }//GEN-LAST:event_cmdHistoryActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        this.MiniFrame_History.dispose();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInsuranceActionPerformed
        this.MiniFrame_Insurance.setVisible(true);
    }//GEN-LAST:event_cmdInsuranceActionPerformed

    private void cmdAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAvailableActionPerformed
        this.MiniFrame_Available.setVisible(true);
    }//GEN-LAST:event_cmdAvailableActionPerformed

    private void cmdMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMaintenanceActionPerformed
       this.MiniFrame_Maintenance.setVisible(true);
    }//GEN-LAST:event_cmdMaintenanceActionPerformed

    private void cmdCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCancel1ActionPerformed

    private void cmdCancel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel5ActionPerformed
       this.MiniFrame_Insurance.dispose();
    }//GEN-LAST:event_cmdCancel5ActionPerformed

    private void cmdCancel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel6ActionPerformed
        this.MiniFrame_Maintenance.dispose();
    }//GEN-LAST:event_cmdCancel6ActionPerformed

    private void cmdCancel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel7ActionPerformed
        this.MiniFrame_Rented.dispose();
    }//GEN-LAST:event_cmdCancel7ActionPerformed

    private void cmdCancel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancel8ActionPerformed
        this.MiniFrame_Available.dispose();
    }//GEN-LAST:event_cmdCancel8ActionPerformed

    private void cmdClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClose1ActionPerformed
        this.MiniFrame_Clients.dispose();
    }//GEN-LAST:event_cmdClose1ActionPerformed

    private void cmdClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdClientsMouseClicked
        this.MiniFrame_Clients.setVisible(true);
    }//GEN-LAST:event_cmdClientsMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JInternalFrame MiniFrame;
    private javax.swing.JInternalFrame MiniFrame_Available;
    private javax.swing.JInternalFrame MiniFrame_Clients;
    private javax.swing.JInternalFrame MiniFrame_History;
    private javax.swing.JInternalFrame MiniFrame_Insurance;
    private javax.swing.JInternalFrame MiniFrame_Maintenance;
    private javax.swing.JInternalFrame MiniFrame_NewCar;
    private javax.swing.JInternalFrame MiniFrame_New_Staff;
    private javax.swing.JInternalFrame MiniFrame_Rented;
    private javax.swing.JInternalFrame MiniFrame_StaffRecords;
    private javax.swing.JInternalFrame MiniFrame_Staff_Records;
    private javax.swing.JPanel New_Staff;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JMenuItem cmdAvailable;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdCancel1;
    private javax.swing.JButton cmdCancel2;
    private javax.swing.JButton cmdCancel3;
    private javax.swing.JButton cmdCancel4;
    private javax.swing.JButton cmdCancel5;
    private javax.swing.JButton cmdCancel6;
    private javax.swing.JButton cmdCancel7;
    private javax.swing.JButton cmdCancel8;
    private javax.swing.JMenu cmdClients;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdClose1;
    private javax.swing.JMenuItem cmdFinance;
    private javax.swing.JMenuItem cmdHistory;
    private javax.swing.JMenu cmdHome;
    private javax.swing.JMenuItem cmdInsurance;
    private javax.swing.JMenu cmdMaintain;
    private javax.swing.JMenuItem cmdMaintenance;
    private javax.swing.JMenu cmdMgt;
    private javax.swing.JMenuItem cmdNewCar;
    private javax.swing.JMenuItem cmdNew_Staff;
    private javax.swing.JButton cmdOk;
    private javax.swing.JButton cmdOk1;
    private javax.swing.JButton cmdOk2;
    private javax.swing.JMenuItem cmdRented;
    private javax.swing.JButton cmdSave;
    private javax.swing.JButton cmdSave1;
    private javax.swing.JMenu cmdStaff;
    private javax.swing.JMenuItem cmdStaff_Records;
    private javax.swing.JMenu cmdVehicle;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTabbedPane tabBankAcc;
    private javax.swing.JTabbedPane tabBills;
    private javax.swing.JTabbedPane tabFinance;
    private javax.swing.JTable tblRented;
    private javax.swing.JTable tblRented1;
    private javax.swing.JTable tblRented2;
    private javax.swing.JTable tblRented3;
    private javax.swing.JTable tblRented5;
    private javax.swing.JTable tblStaff_Records;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
